[package]
name = "rs-plugin-openlibrary"
version = "0.1.2"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
extism-pdk = "1.4.1"
rs-plugin-common-interfaces = "0.27.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
extism = "1"
